baseURL = "http://epages-de.github.io/google-smart-shopping-workshop"
languageCode = "de-de"
title = "Smart Shopping"
theme = "workshop-materials"
defaultContentLanguage = "de"

[params]
  subject = "Smart Shopping"
  feedbackLink = "mailto:info@epages.com"
