baseURL = "https://docs.vm-intern.epages.com/google-smart-shopping"
languageCode = "de-de"
title = "My New Hugo Site"
theme = "workshop-materials"
defaultContentLanguage = "de"

[params]
  subject = "Google Smart Shopping"
  feedbackLink = "mailto:info@epages.com"
