baseURL = "https://jmewes.github.io/ep-google-smart-shopping"
languageCode = "de-de"
title = "My New Hugo Site"
theme = "workshop-materials"
defaultContentLanguage = "de"

[params]
  subject = "Google Smart Shopping"
  feedbackLink = "mailto:info@epages.com"
